### ISSUE TITLE
HandShake Tools menu and Capture data menu will run into an error

### ISSUE THREAD

**Issue by D4MI4NX** [DEADSEC-SECURITY/CODEX#14]
When you try to get into the "HandShake Tools menu" or "Capture data menu" you will get:

(HandShake Tools menu:)

Traceback (most recent call last):
  File "/home/kali/CODEX/./codex.py", line 404, in HANDSHAKE
    ListDir = os.listdir(Dir)
FileNotFoundError: [Errno 2] No such file or directory: 'Data/HandShakes'

(Capture data menu:)

Traceback (most recent call last):
  File "/home/kali/CODEX/./codex.py", line 578, in DataCaptureMenu
    ListDir = os.listdir(Dir)
FileNotFoundError: [Errno 2] No such file or directory: 'Data/CaptureData'

OS = Kali 2022.3
Computer = Raspberry Pi 4

To fix this you just need to add the directorys "HandShakes" and "CaptureData" into the Data directory

**Comment by DEADSEC-SECURITY** [comment]
Hey @D4MI4NX thanks for reporting this issue.
I have stopped supporting CODEX full-time but ill get this fixed :)

**Comment by DEADSEC-SECURITY** [comment]
Fixed :)
